version: '3.8'

networks:
  es:
    external: true

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: kibana
    restart: always
    volumes:
      - ./kibana/config:/usr/share/kibana/config
      - ./kibana/data:/usr/share/kibana/data
    environment:
      - i18n.locale=zh-CN
    networks:
      - es
    ports:
      - 5601:5601
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: es
    restart: always
    networks:
      - es
    environment:
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - ./esdata1:/usr/share/elasticsearch/data